version: '3'
services:
  app:
    container_name: express-mongo
    restart: always
    build: express-api
    command: nodemon index.js
    ports:
      - '3000:3000'
    volumes:
      - ./express-api:/api
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:4.2
    ports:
      - '27017:27017'
